export const TOGGLE_BOXED_LAYOUT = 'TOGGLE_BOXED_LAYOUT';
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSED_NAV';
export const TOGGLE_NAV_BEHIND = 'TOGGLE_NAV_BEHIND';
export const TOGGLE_FIXED_HEADER = 'TOGGLE_FIXED_HEADER';
export const CHANGE_SIDEBAR_WIDTH = 'CHANGE_SIDEBAR_WIDTH';
export const CHANGE_COLOR_OPTION = 'CHANGE_COLOR_OPTION';
export const CHANGE_THEME = 'CHANGE_THEME';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_SUCCESS_USER = 'FETCH_SUCCESS_USER';
export const FETCH_ERROR_USER = 'FETCH_ERROR_USER';

export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_SUCCESS_PRODUCT = 'FETCH_SUCCESS_PRODUCT';
export const FETCH_ERROR_PRODUCT = 'FETCH_ERROR_PRODUCT';
export const FETCH_ALLPRODUCTS = 'FETCH_ALLPRODUCTS';
export const FETCH_SUCCESS_ALLPRODUCTS = 'FETCH_SUCCESS_ALLPRODUCTS';
export const FETCH_ERROR_ALLPRODUCTS = 'FETCH_ERROR_ALLPRODUCTS';

export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';
export const FETCH_SUCCESS_ACCOUNTS = 'FETCH_SUCCESS_ACCOUNTS';
export const FETCH_ERROR_ACCOUNTS = 'FETCH_ERROR_ACCOUNTS';
export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';
export const FETCH_SUCCESS_TRANSACTIONS = 'FETCH_SUCCESS_TRANSACTIONS';
export const FETCH_ERROR_TRANSACTIONS = 'FETCH_ERROR_TRANSACTIONS';

export const BUY_PRODUCT = 'BUY_PRODUCT';
export const BUY_PRODUCT_SUCCESS = 'BUY_PRODUCT_SUCCESS';
export const BUY_PRODUCT_ERROR = 'BUY_PRODUCT_ERROR';

export const TRANSFER_MONEY = 'TRANSFER_MONEY';
export const TRANSFER_MONEY_SUCCESS = 'TRANSFER_MONEY_SUCCESS';
export const TRANSFER_MONEY_ERROR = 'TRANSFER_MONEY_ERROR';
